import type { PhysicalDelivery } from '@/types/Tracking'

export const MOCK_DELIVERIES: PhysicalDelivery[] = [
  {
    id: 'del-1',
    employee: 'Chinedu Balogun',
    item: 'Welcome Onboarding Pack',
    status: 'In Transit',
    courier: 'GIG Logistics',
    trackingRef: 'GB-2381',
    eta: 'Arriving tomorrow, by 6:00 PM',
    steps: [
      { label: 'Order placed', timestamp: 'Jul 9, 9:02 AM', completed: true },
      { label: 'Processing', timestamp: 'Jul 9, 11:40 AM', completed: true },
      { label: 'Dispatched', timestamp: 'Jul 10, 8:15 AM', completed: true },
      { label: 'In transit', timestamp: 'Jul 10, 2:30 PM', completed: true },
      { label: 'Out for delivery', timestamp: 'Expected Jul 11', completed: false },
      { label: 'Delivered', timestamp: '—', completed: false },
    ],
  },
  {
    id: 'del-2',
    employee: 'Tobi Fashola',
    item: 'Custom Gift Pack',
    status: 'Delivered',
    courier: 'Kwik Delivery',
    trackingRef: 'GB-2290',
    eta: 'Delivered Jul 6, 3:12 PM',
    steps: [
      { label: 'Order placed', timestamp: 'Jul 3, 10:00 AM', completed: true },
      { label: 'Processing', timestamp: 'Jul 3, 1:20 PM', completed: true },
      { label: 'Dispatched', timestamp: 'Jul 4, 9:00 AM', completed: true },
      { label: 'In transit', timestamp: 'Jul 5, 11:00 AM', completed: true },
      { label: 'Out for delivery', timestamp: 'Jul 6, 9:40 AM', completed: true },
      { label: 'Delivered', timestamp: 'Jul 6, 3:12 PM', completed: true },
    ],
  },
  {
    id: 'del-3',
    employee: 'Ibrahim Suleiman',
    item: 'Compensation Voucher Pack',
    status: 'Processing',
    courier: 'Sendbox',
    trackingRef: 'GB-2402',
    eta: 'Estimated dispatch in 1-2 days',
    steps: [
      { label: 'Order placed', timestamp: 'Jul 10, 4:45 PM', completed: true },
      { label: 'Processing', timestamp: 'Jul 11, 8:00 AM', completed: true },
      { label: 'Dispatched', timestamp: 'Expected Jul 12', completed: false },
      { label: 'In transit', timestamp: '—', completed: false },
      { label: 'Out for delivery', timestamp: '—', completed: false },
      { label: 'Delivered', timestamp: '—', completed: false },
    ],
  },
]
